Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 159, in <module>
    pycron.start()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 104, in start
    time.sleep(1 - (end_time - start_time))
KeyboardInterrupt
Exception ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1583, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Traceback (most recent call last):
  File "/var/pythonapps/downloadFiles.py", line 3, in <module>
    import pycron
ModuleNotFoundError: No module named 'pycron'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/var/pythonapps/.venv/lib/python3.11/site-packages/pycron/__init__.py", line 24, in run
    asyncio.run(self.function(datetime.now()))
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/var/pythonapps/downloadFiles.py", line 160, in downloadFiles
    ModifyFiles().apolloMod()
  File "/var/pythonapps/Classes/ModifyFiles.py", line 73, in apolloMod
    subst_dict['ean'] = item['EAN']
                        ~~~~^^^^^^^
KeyError: 'EAN'
